### ISSUE TITLE
R-8 split by battalion line

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#101]
via @slocoff ... I'll leave this for you and @888Akasha

**Comment by 888Akasha** [comment]
Realigned Battalion 3/5 line around R-8. Realigned atom lines and city lines to battalion line. Center-lined atom/city/batt lines around R-8 where appropriate.

**Comment by 888Akasha** [comment]
Batt line slightly different than planned to follow atoms/parcels/topo.

Edited:
![image](https://cloud.githubusercontent.com/assets/6013706/6982321/16cf743e-d9c5-11e4-873b-49eb0d71ee30.png)

Planned:
![image](https://cloud.githubusercontent.com/assets/6013706/6982339/53991258-d9c5-11e4-9778-a8a51e89ed42.png)
