### ISSUE TITLE
11931 Huasna River Rd

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#108]
Attached is screenshots showing the correct location of 11931 Huasna River Rd.

The house is up an unamed dirt road, but the parcel crosses Huasna River Rd., probably causing the address to trigger a Huasna River Rd. address.  The situs is different also.  This is an old old homestead with a newer doublewide.

The house is marked correctly with numbers, but you would have no way of knowing that from Huasna River Rd.

![11931huasnariver](https://cloud.githubusercontent.com/assets/271851/6872042/e4677a02-d463-11e4-97b3-9383649e42c2.png)

@888Akasha I'm still looking into this but wondering if it might need a CPN?

**Comment by 888Akasha** [comment]
The parcel shown is at Huasna River Rd. and Deer Creek Rd. Best bet would be to use an LOI giving directions to the location. Was homeowner told to fix?

**Comment by 888Akasha** [comment]
Added as an LOI in CAD

**Comment by oeon** [comment]
road address range optimized
