### ISSUE TITLE
Tower Rd

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#118]
All Addresses on the north side of Tower Rd. between Airport Rd. and Jardine Rd. are verifying inside Paso City jurisdiction. Address range 3300 thru 5000.
![tower_rd](https://cloud.githubusercontent.com/assets/271851/7817710/a976a1a0-038b-11e5-8ff6-26fbc8d0c135.png)
@888Akasha @slocoff guessing this is a City issue. Please advise if it's not.

**Comment by 888Akasha** [comment]
City & atom lines are centerlined. PRF addresses are verifying as SLO_CO and SLO_CO addresses are verifying as PRF. Check road segment addressing?

**Comment by oeon** [comment]
flipped segment, what a stinker!
