### ISSUE TITLE
Landing Passage, Avila

### ISSUE THREAD

**Issue by 888Akasha** [SLUGIS/CAD#134]
Add address range. Appears to be communal driveway, but residences are individually addressed.

![landing passage](https://cloud.githubusercontent.com/assets/6013706/9156226/3499af12-3e87-11e5-8495-e78e434f2a9d.png)

**Comment by 888Akasha** [comment]
Business, not residences...

Salon Om: 56 Landing Passage St.
Sayva: 65 Landing Passage St.
Wally's Bicycle Rental: 66 Landing Passage St.
Taco Shack: 86 Landing Passage St.
2nd Chance Winery: 65 Landing Passage St.
Morovino Winery: 76 Landing Passage St.

**Comment by oeon** [comment]
range added
