### ISSUE TITLE
Avila Beach Dr.

### ISSUE THREAD

**Issue by 888Akasha** [SLUGIS/CAD#135]
Address range for south end of Avila Beach Dr. is incorrect.

3950 Avila Beach Dr. (Harbor Office)
![image](https://cloud.githubusercontent.com/assets/6013706/9158427/a5200814-3ecb-11e5-9dc3-cc86a568773e.png)

3920 Avila Beach Dr. (Fat Cats)
![image](https://cloud.githubusercontent.com/assets/6013706/9158461/2959f0d6-3ecc-11e5-86ef-3da651ca9d6d.png)

**Comment by 888Akasha** [comment]
Also:
Avila Beach Paddlesports: 3915 Avila Beach Dr.
Portside Coffee: 3915 Avila Beach Dr.

**Comment by oeon** [comment]
range adjusted
