### ISSUE TITLE
1021 South Halcyon

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#155]
Odd address from 900blk to 1200blk need GEO as county. Had a call at 1091 S Halcyon and GEOd as OCE. 

![1021_south_halcyon](https://cloud.githubusercontent.com/assets/271851/11798312/79ae3b44-a27e-11e5-9d4e-6617743fef62.png)

**Comment by 888Akasha** [comment]
This is the only part of 5 cities that hasn't been centerlined. Lot of history here back and forth on what addresses are in the city and what are ours. Do we know how accurate the city line is as far as parcels go?

**Comment by oeon** [comment]
I simply centerlined it for now…will let you fix as you see fit, when you return. I think that line is the best info we have and is accurate.

**Comment by 888Akasha** [comment]
Copy. Thanks!

**Comment by oeon** [comment]
fixed this like I've fixed the other similar issues: what is technically the city limit versus what we need for centerline-geolocating. Details in the 'DESCRIPTION' field...

![halcyon_oce_slo-co](https://cloud.githubusercontent.com/assets/271851/11818442/331dfd7c-a30f-11e5-8729-69b9dcb4d3d3.JPG)
