### ISSUE TITLE
Village Circle

### ISSUE THREAD

**Issue by 888Akasha** [SLUGIS/CAD#156]
New development needs to be added to CAD

![image](https://cloud.githubusercontent.com/assets/6013706/12317408/e4fa4792-ba45-11e5-8867-28c484a11bd5.png)

![image](https://cloud.githubusercontent.com/assets/6013706/12317417/f943dd1c-ba45-11e5-897d-ce83d1bc8ded.png)

**Comment by oeon** [comment]
we're working on it http://www.openstreetmap.org/#map=18/35.13205/-120.60807 construction is not fully complete...but we'll take another field trip out there soon

**Comment by 888Akasha** [comment]
We had a 911 out there. Looks like at least a few people are moving in. Can we can a 0 range for the street so we can verify calls for now?

**Comment by oeon** [comment]
yes, will get on it rn

**Comment by oeon** [comment]
Sitting on 99. It passed GUT for me...but I'd do all the GUT steps when you do the push. I'll leave this Issue for you to close once it fully goes through.

**Comment by 888Akasha** [comment]
The new Branch Rd. split the segment of Oak Park Blvd. it connected to, so there are now 2 segments of Oak Park Blvd. with the same address range. There's nothing on the southern segment, so if we change that to a 0 range it should fix it. It's causing a couple CPNs to error out, so I'll hold off on the push for now.

![image](https://cloud.githubusercontent.com/assets/6013706/12370659/facb546a-bbcd-11e5-9bab-ddbf8b815d9c.png)

**Comment by 888Akasha** [comment]
All segments of Oak Park had address ranges. Made the segment between NB 101 & SB 101 the 0-0 range, and moved each subsequent range north one up through the duplicate.

**Comment by oeon** [comment]
On the County side, I have copied what you did to SEG_ID = 910468 which was changing R_F_ADD & R_T_ADD = 818 and L_F_ADD & L_T_ADD = 819. So if this is working for you, works for me. Can we close this yet?

**Comment by oeon** [comment]
This is a weird way to do address ranges...especially with how our CAD works. It'll get them close.

![thevillageatpacificwest](https://cloud.githubusercontent.com/assets/271851/12434857/57947bd4-bebe-11e5-84a9-2f551f733ac4.JPG)
