### ISSUE TITLE
Vista Tesoro Pl

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#163]
got a call from an alarm company to verify jurisdiction at 1428 Vista Tesoro Pl. but it appears there’s no address range yet

![vistatesoro](https://cloud.githubusercontent.com/assets/271851/12984672/b08a8b92-d0a3-11e5-9112-fe994c344653.jpg)

**Comment by 888Akasha** [comment]
Seg 910401
  Flip seg.
  LF 1389
  LT 1473
  RF 1395
  RT 1494

Seg 910400
  Flip seg.
  LF 1503
  LT 1557
  RF 1500
  RT1524

**Comment by 888Akasha** [comment]
Duplicated address range. Updated.
