### ISSUE TITLE
New city data

### ISSUE THREAD

**Issue by 888Akasha** [SLUGIS/CAD#167]
Realign cities and atoms to new city data

**Comment by 888Akasha** [comment]
Need to complete:
Morro Bay
Paso Robles
Atascaero
San Luis Obispo
Pismo Beach
Grover Beach
Arroyo Grande

**Comment by oeon** [comment]
I made fancy check boxes with your issue 😉 https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments
