### ISSUE TITLE
Sand Hwy

### ISSUE THREAD

**Issue by hpanno** [SLUGIS/CAD#185]
Add Sand Highway, Pismo Dunes

**Comment by 888Akasha** [comment]
Sand Highway exists as a trail it looks like. Should probably be changed to Sand Hwy to match naming convention. Was there an issue with the road? Or are we good?

![sand hwy](https://cloud.githubusercontent.com/assets/6013706/18403164/194198f2-7698-11e6-9b03-4ffae2a19595.png)

**Comment by oeon** [comment]
Trails aren't 'route-able' in CAD, right @888Akasha ? I.e. CAD won't route a vehicle up those road segments? Maybe @hpanno can share the need/issue this arose from..

**Comment by hpanno** [comment]
From what I understand, the Nipomo Station wants Sand Hwy routed because that area gets quite a bit of traffic. I will confirm with Dave.

**Comment by 888Akasha** [comment]
OK. That makes sense. So we just need to change from trail to road then.

**Comment by 888Akasha** [comment]
Edits to Beach Access & Sand Highway

Seg 910490 - FCC P05
Seg 910491 - FCC P05
Seg 910492 - FCC P05, Name SAND HWY, Label Sand Hwy
Seg 910493 - FCC P05, Name SAND HWY, Label Sand Hwy
Seg 910494 - FCC P05, Name SAND HWY, Label Sand Hwy

**Comment by 888Akasha** [comment]
Push to CAD complete. Need to test routing. May need to adjust road speeds.

**Comment by 888Akasha** [comment]
Sand Hwy road speeds adjusted to 25
Conoco Access Rd speed adjusted to 25

**Comment by hpanno** [comment]
All issues & edits have been addressed.
