### ISSUE TITLE
BC Atoms

### ISSUE THREAD

**Issue by 888Akasha** [SLUGIS/CAD#198]
Delete Station BC Atoms

**Comment by 888Akasha** [comment]
Atoms deleted:
![image](https://cloud.githubusercontent.com/assets/6013706/18560225/85cc4e5e-7b2f-11e6-9aca-4e8f38089a37.png)

Delete RAR, ATM, RGP, any SRPs. Change BC default locations on RES to Station RAR

**Comment by 888Akasha** [comment]
Push to CAD complete. Need to finish CAD admin work

**Comment by hpanno** [comment]
These edits have been completed by @888Akasha
