### ISSUE TITLE
836 N Oak Park Blvd

### ISSUE THREAD

**Issue by slocoff** [SLUGIS/CAD#207]
Ross in Pismo is 836 N Oak Park but GEO's in CAD as AG not PB. Address range needs to be adjusted to PB

#firstgithubpost

**Comment by hpanno** [comment]
I will take a look, thanks Michael! #ProudMoments!

**Comment by hpanno** [comment]
@slocoff , I see that Ross in Pismo Beach should be at: 829 N Oak Park Blvd, Pismo Beach, CA 93449 --> based on the current address ranges that address should GEO correctly in CAD - let me know if you experience any issues with the updated address. 


![pismobeachross](https://cloud.githubusercontent.com/assets/1495756/19653824/d708b118-99ca-11e6-9245-2ef22938f5d5.png)

**Comment by slocoff** [comment]
This is how it was sent over from Pismo. So looks like either they typo'd or was given the wrong address.  As long as the ranges match up, probably good to go.
![image](https://cloud.githubusercontent.com/assets/6879590/19655605/84fb2642-99d1-11e6-9557-8472a9635fe0.png)

**Comment by hpanno** [comment]
@slocoff yes, the address above is close - the intersection adjacent to the actual location. Since the actual address for this location falls in the appropriate range I think this area is ok. But if any other issues come up for this one, please let me know!
