### ISSUE TITLE
A-17, A-38 atoms

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#22]
A-17 needs to be split where Battalion line crosses.

A-17, A-38 RAR's need to be changed from Batt2->1

**Comment by 888Akasha** [comment]
RAR's done. Still need to split A-17.

**Comment by 888Akasha** [comment]
@oeon Do you have any other details on this? Or is it just a straight uncomplicated split?

**Comment by 888Akasha** [comment]
Part of larger consolidation project. Will be documented with the rest of the project.
