### ISSUE TITLE
Duplicate address ranges Hwy 46W

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#24]
SEG_ID = 909713 OR SEG_ID = 909479 OR SEG_ID = 909480 OR SEG_ID = 909481 OR SEG_ID = 909482 OR SEG_ID = 909483 OR SEG_ID = 909484 OR SEG_ID = 909485 OR SEG_ID = 909486

**Comment by hpanno** [comment]
Appears to have been resolved.
