### ISSUE TITLE
Rocky Canyon

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#47]
@888Akasha or @oeon 

         In the Cad map we need to update the cross streets of Rocky Canyon Rd. in Atascadero. We have found that the Rocky Canyon Rd. in Creston has brought upon some confusion as to what area it is when you cannot verify an appropriate cross street with a caller. I have went through CAD and came up with cross streets for the blocks listed below. Let me know if this works. Thank you

 4900 Blk. of Rocky Canyon needs a (High) cross street added.    Should look like - 3101 BLK CRESTON EUREKA RD / 3000 BLK RIO VISTA

 5000 thru 5800 Blks. of Rocky Canyon needs a (High) cross street added. Should look like - 3000 BLK RIO VISTA / 3300 BLK ADOBE CANYON RD

 5900 thru 6500 Blks. Of Rocky Canyon need both (High) and (Low) cross streets added.        Should look like - 3000 BLK RIO VISTA / 3300 BLK ADOBE CANYON RD

 6600 thru 6800 Blks. Of Rocky Canyon needs a (Low) cross street added.  Should look like - 3000 BLK RIO VISTA / 3300 BLK ADOBE CANYON RD

 Chad Mitchell

**Comment by 888Akasha** [comment]
Emails indicate we decided to leave as is Jan. 2015
