### ISSUE TITLE
Embarcadero Rd. & Front St., Morro Bay

### ISSUE THREAD

**Issue by 888Akasha** [SLUGIS/CAD#68]
Embarcadero & Front St. run parallel, join together, then split again. The segment at which they join together needs to be changed from Front St. to Embarcadero. Cross street is Beach St.

![image](https://cloud.githubusercontent.com/assets/6013706/3638617/7988ab2e-1056-11e4-9b73-baf227bb9b37.png)

**Comment by hpanno** [comment]
Appears to have been resolved.
