### ISSUE TITLE
18721 & 18725 Hwy 101

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#92]
Yesterday we had a control burn at 18725 Hwy 101, North side of the grade and S/E of Tassajara Crk Rd.. The APN info says “El Camino Real” which we know is Hwy 101 but if you were to try an enter those address as ECR, it comes up wrong North of Margarita.  
 
Can a block range be added in for these two addresses on that portion of 101? Chief Tully spoke to the resident and they gave Hwy 101 not El Camino Real. As of now, we’d have to go off directions to get there as we have no way to GEO correctly.
![18721_18725hwy101](https://cloud.githubusercontent.com/assets/271851/5572865/46b62be0-8f59-11e4-85d4-7e05502fd4f4.png)

**Comment by 888Akasha** [comment]
Rd seg 903222 split at atom line K10/K-15B
South section stays the same
North section new seg id 910499, no address range label
  LF 0
  LT 0
  RF 18725
  RT 18781
