### ISSUE TITLE
21890 J St., Santa Margarita

### ISSUE THREAD

**Issue by oeon** [SLUGIS/CAD#98]
An alarm co called in to verify jurisdiction and the numerics didn’t verify in CAD. The address given was 21890 J St., Santa Margarita. I confirmed the cross-street of Hwy 58.

**Comment by 888Akasha** [comment]
Confirm road seg. break at SMV city line

**Comment by 888Akasha** [comment]
Rd seg 910088 & 910089 re-snap to Santa Margarita city line

**Comment by 888Akasha** [comment]
Check if J St. alias works in CAD

**Comment by 888Akasha** [comment]
Alias updated
